services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173' # vite dev server uses this port
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: bun run dev
