services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - '5173:5173'
      - '24678:24678' # HMR port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
